// <auto-generated />
using System;
using Gerencial.WebApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Gerencial.WebApi.Migrations
{
    [DbContext(typeof(GerencialContext))]
    [Migration("20210831212455_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Gerencial.WebApi.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Nome")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("Tbl_Clientes");
                });

            modelBuilder.Entity("Gerencial.WebApi.Models.Intervencao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DtServico")
                        .HasColumnType("datetime2");

                    b.Property<string>("Solicitacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Solicitador")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Tbl_Intervencoes");
                });

            modelBuilder.Entity("Gerencial.WebApi.Models.Intervencao", b =>
                {
                    b.HasOne("Gerencial.WebApi.Models.Cliente", "Cliente")
                        .WithMany("Intervencoes")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Gerencial.WebApi.Models.Cliente", b =>
                {
                    b.Navigation("Intervencoes");
                });
#pragma warning restore 612, 618
        }
    }
}
